name: Pterodactyl PHP (linux/arm/v7, linux/arm/v8, linux/arm64)

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - php/**

jobs:
  push:
    name: "PHP-${{ matrix.version }}"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        version:
          - 8-3_arm
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./php
          file: ./php/${{ matrix.version }}/Dockerfile
          platforms: linux/arm/v8,linux/arm/v7,linux/arm64
          push: true
          tags: |
            ghcr.io/medaria/pterodactyl-php-arm-${{ matrix.version }}
